studentdb/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'site/index'
  get 'site/admin_dashboard', as: :admin_dashboard
  resources :projects
  root to: 'site#index'
end

studentdb/app/models/application_record.rb
# frozen_string_literal: true

# Superclass for all active record models
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

studentdb/app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :url
end

studentdb/app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
end

studentdb/app/models/user.rb
# frozen_string_literal: true

# User model active record
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  before_save :make_first_user_an_admin

  protected

  # If there are no users yet, make this user an admin

  def make_first_user_an_admin
    return unless User.count.zero?

    self.is_admin = true
  end
end

studentdb/app/controllers/application_controller.rb
# frozen_string_literal: true

# Top-level superclass of all controllers
class ApplicationController < ActionController::Base
  include Pundit
end

studentdb/app/controllers/projects_controller.rb
# frozen_string_literal: true

# Controller for the projects resource
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :url)
  end
end

studentdb/app/controllers/site_controller.rb
# frozen_string_literal: true

# Top-level site controller
class SiteController < ApplicationController
  def index; end

  def admin_dashboard
    authorize :site, :admin_dashboard?
  end
end

studentdb/app/helpers/application_helper.rb
# frozen_string_literal: true

# Top-level helper module
module ApplicationHelper
end

studentdb/app/helpers/projects_helper.rb
# frozen_string_literal: true

# Helpers for projects controller
module ProjectsHelper
end

studentdb/app/helpers/site_helper.rb
# frozen_string_literal: true

# Helpers for the site controller
module SiteHelper
end

studentdb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student Database</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:error] %>
      <div id="error">
        <%= flash[:error] %>
      </div>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div id="container">
      <div id="user_status">
        <% if user_signed_in? %>
          Welcome <%= current_user.email %>! Not you?
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or
          <%= link_to "Sign in", new_user_session_path %>.
        <% end %>
        <% if current_user&.is_admin %>
          <%= link_to "Admin dashboard", admin_dashboard_path %>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>

</html>

studentdb/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

studentdb/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

studentdb/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.url %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

studentdb/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

studentdb/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @project.url %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

studentdb/app/views/site/admin_dashboard.html.erb
<h1>Admin dashboard</h1>

studentdb/app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>